let database = [];

// 1. Load the search index database (database.json) generated by your Python script
fetch('database.json')
  .then(response => {
    if (!response.ok) {
      throw new Error('Failed to load database.json. Make sure the file exists.');
    }
    return response.json();
  })
  .then(data => {
    database = data;
    
    // Enable the search button once the data is fully loaded
    const btn = document.getElementById('search-btn');
    if (btn) {
      btn.disabled = false;
      btn.innerText = 'Search';
    }
  })
  .catch(error => {
    console.error('Error loading database:', error);
    const btn = document.getElementById('search-btn');
    if (btn) {
      btn.innerText = 'Database Error';
    }
  });

const form = document.getElementById('search-form');
const resultsDiv = document.getElementById('results');

// 2. Handle the search form submission
form.addEventListener('submit', (e) => {
  e.preventDefault();
  
  const query = document.getElementById('search-input').value.trim().toLowerCase();
  resultsDiv.innerHTML = ''; // Clear any previous search results

  if (!query) return;

  // Filter the database array for partial name matches (case-insensitive)
  const matches = database.filter(item => item.name.toLowerCase().includes(query));

  // If no matching participants are found
  if (matches.length === 0) {
    resultsDiv.innerHTML = `<p class="no-results">No matches found for "${document.getElementById('search-input').value}". Please check your spelling.</p>`;
    return;
  }

  // 3. Display the matching student profiles
  matches.forEach(match => {
    const card = document.createElement('div');
    card.className = 'result-card';

    // Handle empty or "nan" ID strings safely
    const cleanId = (match.id && match.id.toLowerCase() !== 'nan' && match.id !== "") ? match.id : '';
    const idInfo = cleanId ? ` | ID: ${cleanId}` : '';
    
    // Create bullet points for each event they participated in
    const eventsList = match.events
      .map(event => `<li>${event}</li>`)
      .join('');

    card.innerHTML = `
      <h3>${match.name}</h3>
      <p class="meta">Class: ${match.class} | Section: ${match.section}${idInfo}</p>
      <div class="downloads">
        <p><strong>Participated in:</strong></p>
        <ul style="margin: 0 0 16px 0; padding-left: 20px;">
          ${eventsList}
        </ul>
        <a href="certificates/${match.zip_file}" download class="download-btn">
          Download All Certificates (ZIP)
        </a>
      </div>
    `;
    resultsDiv.appendChild(card);
  });
});